### ISSUE TITLE
help

### ISSUE THREAD

**Issue by smr02** [K1DV5/docal-tkinter#1]
`Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\anaconda3\lib\site-packages\docal_tkinter\__main__.py", line 6, in <module>
    app = App()
  File "C:\Users\user\anaconda3\lib\site-packages\docal_tkinter\app.py", line 25, in __init__
    self.worksheet = Worksheet(self)
  File "C:\Users\user\anaconda3\lib\site-packages\docal_tkinter\worksheet.py", line 63, in __init__
    self.update_above(first)  # to include the math functions
  File "C:\Users\user\anaconda3\lib\site-packages\docal_tkinter\worksheet.py", line 109, in update_above
    self.process('from math import *')  # scientific math funcs
  File "C:\Users\user\anaconda3\lib\site-packages\docal\processing.py", line 92, in process
    for part in _get_parts(parts):
  File "C:\Users\user\anaconda3\lib\site-packages\docal\parsing.py", line 737, in _get_parts
    line = p.end_lineno + 1
AttributeError: 'ImportFrom' object has no attribute 'end_lineno'`

**Comment by K1DV5** [comment]
Sorry for the late reply, I'll look into it
